input_dir = 'input'
output_dir = 'output'
package_name = 'stdgui.data.model.orimodel'
wrapper_package_name = 'stdgui.data.model.modelwrapper'
element_wrapper = 'true'
ExtractInnerClass = 'true'
generate_wrapper = 'true'