input_dir = 'input'
output_dir = 'output'
package_name = 'stdgui.data.entity.schema'
wrapper_package_name = 'stdgui.data.entity.schema.wrapper'
element_wrapper = 'true'
ExtractInnerClass = 'true'
generate_wrapper = 'true'